### ISSUE TITLE
Update `Compiler.link_graph()` method, bump package to require dbt 1.6

### ISSUE THREAD

**Issue by dave-connors-3** [dbt-labs/dbt-meshify#116]
@nicholasyager happy to open this as a new issue, but I ran that same command on your new ChangeSet branch and received a new and different error!

```bash
❯ dbt-meshify split joe --select +current_snowplow_event scrubbed_learn_snowplow_events --read-catalog
16:11:04 | INFO | Executing dbt parse...
16:11:06 | INFO | Reading catalog from /Users/daveconnors/dev/dbt-labs/internal-analytics/target/catalog.json
16:11:11 | DEBUG | Registering the relationship between joe and its resources
16:11:11 | INFO | Selected 27 resources: {'snapshot.fishtown_internal_analytics.single_tenant_mappings_snapshot', 'test.fishtown_internal_analytics.not_null_single_tenant_mappings_id.9ff415803a', 'model.fishtown_internal_analytics.current_snowplow_event', 'model.fishtown_internal_analytics.stg_googlesheets__singletenant_lookup', 'test.fishtown_internal_analytics.source_snowplow_app_recency_snowplow_event_dbt_docs__48_hours.e05efc1dca', 'source.fishtown_internal_analytics.snowplow.event', 'test.fishtown_internal_analytics.unique_single_tenant_mappings_mapping_value.6985dd6462', 'test.fishtown_internal_analytics.unique_stg_cloud_s3_single_tenant_docs_single_tenant_name.4f3bdad82a', 'model.fishtown_internal_analytics.single_tenant_mappings', 'test.fishtown_internal_analytics.not_null_current_snowplow_event_event_id.30c9897404', 'model.fishtown_internal_analytics.scrubbed_learn_snowplow_events', 'test.fishtown_internal_analytics.not_null_single_tenant_mapping_unioned_unique_id.e80ea722a3', 'test.fishtown_internal_analytics.source_snowplow_app_recency_snowplow_event_dbt__48_hour.e7ada201bc', 'source.fishtown_internal_analytics.cloud_s3_single_tenant_docs.configs', 'test.fishtown_internal_analytics.unique_stg_cloud_s3_single_tenant_docs_database_source.1b1b02d141', 'test.fishtown_internal_analytics.not_null_stg_cloud_s3_single_tenant_docs_database_source.2e8c8fe417', 'test.fishtown_internal_analytics.unique_current_snowplow_event_event_id.c7841f6069', 'test.fishtown_internal_analytics.not_null_stg_cloud_s3_single_tenant_docs_single_tenant_name.a77cb3cc01', 'test.fishtown_internal_analytics.source_snowplow_app_recency_snowplow_event_getdbt_com__48_hours.939419613a', 'test.fishtown_internal_analytics.unique_single_tenant_mapping_unioned_mapping_value.9ab936e7d3', 'model.fishtown_internal_analytics.single_tenant_mapping_unioned', 'model.fishtown_internal_analytics.stg_cloud_s3_single_tenant_docs', 'source.fishtown_internal_analytics.fivetran_googlesheets.singletenant_ips', 'test.fishtown_internal_analytics.unique_single_tenant_mapping_unioned_unique_id.3e3b3eb60e', 'test.fishtown_internal_analytics.source_snowplow_app_recency_snowplow_event_discourse_getdbt_com__48_hours.3379341a29', 'seed.fishtown_internal_analytics.stg_seed__mt_multiregion_mappings', 'test.fishtown_internal_analytics.unique_single_tenant_mappings_id.118966bed4'}
Traceback (most recent call last):
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/bin/dbt-meshify", line 8, in <module>
    sys.exit(cli())
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/dbt_meshify/main.py", line 164, in split
    subproject_creator = DbtSubprojectCreator(project=subproject, target_directory=create_path)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/dbt_meshify/storage/dbt_project_editors.py", line 113, in __init__
    self.project_boundary_models = self._get_subproject_boundary_models()
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/dbt_meshify/storage/dbt_project_editors.py", line 122, in _get_subproject_boundary_models
    graph=self.project.graph.graph, selected_bunch=nodes
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/dbt_meshify/dbt_projects.py", line 83, in graph
    self._graph = self._load_graph(self.manifest)
  File "/Users/daveconnors/dev/dbt-labs/internal-analytics/env/lib/python3.9/site-packages/dbt_meshify/dbt_projects.py", line 74, in _load_graph
    compiler.link_graph(linker=linker, manifest=manifest)
AttributeError: 'Compiler' object has no attribute 'link_graph'
```

this seems to point to a dbt-core class -- looks like that method got moved to the `Linker` class in dbt version 1.6 -- should be easy enough to update and bump our core dependency version!

_Originally posted by @dave-connors-3 in https://github.com/dbt-labs/dbt-meshify/issues/113#issuecomment-1681403218_

**Comment by dave-connors-3** [comment]
can be completed in #107 if we want!
