### ISSUE TITLE
When running the dbt-meshify connect command, I get an error if I haven't already run dbt deps in all of my projects

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#156]
```
09:35:10 | INFO | Executing dbt parse...
09:35:11 | INFO | Generating catalog with dbt docs generate...
09:35:24 | INFO | Executing dbt parse...
16:35:24  Encountered an error:
Compilation Error
  dbt found 2 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
Traceback (most recent call last):
  File "/Users/gracegoheen/.venv/meshify-current/bin/dbt-meshify", line 6, in <module>
    sys.exit(cli())
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gracegoheen/dev/dbt-meshify/dbt_meshify/main.py", line 142, in connect
    all_dbt_projects = [
  File "/Users/gracegoheen/dev/dbt-meshify/dbt_meshify/main.py", line 143, in <listcomp>
    DbtProject.from_directory(project_path, read_catalog)
  File "/Users/gracegoheen/dev/dbt-meshify/dbt_meshify/dbt_projects.py", line 284, in from_directory
    manifest=dbt.parse(directory),
  File "/Users/gracegoheen/dev/dbt-meshify/dbt_meshify/dbt.py", line 30, in parse
    return self.invoke(directory, ["--quiet", "parse"])
  File "/Users/gracegoheen/dev/dbt-meshify/dbt_meshify/dbt.py", line 25, in invoke
    raise result.exception
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 172, in wrapper
    return func(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 219, in wrapper
    return func(*args, **kwargs)
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/cli/requires.py", line 246, in wrapper
    manifest = ManifestLoader.get_full_manifest(
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/parser/manifest.py", line 307, in get_full_manifest
    projects = config.load_dependencies()
  File "/Users/gracegoheen/.venv/meshify-current/lib/python3.10/site-packages/dbt/config/runtime.py", line 366, in load_dependencies
    raise UninstalledPackagesFoundError(
dbt.exceptions.UninstalledPackagesFoundError: Compilation Error
  dbt found 2 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
```

**Comment by nicholasyager** [comment]
I think this should be a matter of either detecting missing deps or catching the exception, running deps, and then moving on with the original command. Assigning to myself.

**Comment by dave-connors-3** [comment]
@nicholasyager I am bored waiting for a delayed flight! i will take this lil guy!

**Comment by nicholasyager** [comment]
Do it!
