### ISSUE TITLE
Python error on dbt-meshify group

### ISSUE THREAD

**Issue by d-roman-halliday** [dbt-labs/dbt-meshify#186]
### Describe the bug

I'm testing out the new functionality on a demo project on Linux, when I try and run the `group` command, I get the error (full output below):

```
 ERROR | descriptor 'split' for 'str' objects doesn't apply to a 'tuple' object
```

Testing this out with a demo project. Testing with both databases:
- DuckDB
- Postgres

Other info:
- dbt: 1.6.6
- Python is 3.9
- input is all small sample seeds

PostgreSQL version:
```
 PostgreSQL 16.0 (Ubuntu 16.0-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0, 64-bit
(1 row)
```

Based on my standalone project demo: https://github.com/d-roman-halliday/DuckDB-DBT-Example
With added seed files.

### Steps to reproduce
I download my project code, run `bdt build` which works, I then execute the `dbt-meshify group` command and get the error.

### Expected results
The `dbt-meshify` command to update/modify/create `.yml` files as expected in normal operation.

### Actual results
The error is produced on execution.

### Screenshots and log output
```
(venv) david@roman-halliday:~/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo$ dbt-meshify group shopping --select +cart_detail --owner-name "David RH"
```
```
14:31:17 | INFO | Reading dbt project at /home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo
14:31:17 | INFO | Executing dbt parse...
14:31:18 | INFO | Generating catalog with dbt docs generate...
14:31:20 | INFO | Creating new model group in file _groups.yml
14:31:20 | ERROR | descriptor 'split' for 'str' objects doesn't apply to a 'tuple' object
Traceback (most recent call last):

  File "/home/david/Documents/demo-dbt-meshify/venv/bin/dbt-meshify", line 8, in <module>
    sys.exit(cli())
    │   │    └ <Group cli>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x7f21c852ed30>
           └ <Group cli>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x7f21c5c303d0>
         │    └ <function MultiCommand.invoke at 0x7f21c8534d30>
         └ <Group cli>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x7f21c8814e80>
           │               │       │       └ <function Command.invoke at 0x7f21c8534820>
           │               │       └ <TupleCompatibleCommand group>
           │               └ <click.core.Context object at 0x7f21c8814e80>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x7f21c8922040>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
           │   │      │    │           └ <click.core.Context object at 0x7f21c8814e80>
           │   │      │    └ <function group at 0x7f21c4506dc0>
           │   │      └ <TupleCompatibleCommand group>
           │   └ <function Context.invoke at 0x7f21c852e5e0>
           └ <click.core.Context object at 0x7f21c8814e80>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
                       └ ()
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/cli.py", line 123, in wrapper_decorator
    return func(*args, **kwargs)
           │     │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
           │     └ ()
           └ <function group at 0x7f21c4506af0>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           │ │                       │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
           │ │                       └ ()
           │ └ <function get_current_context at 0x7f21c85525e0>
           └ <function group at 0x7f21c4506a60>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/main.py", line 611, in group
    group_changes: List[ChangeSet] = ctx.forward(create_group)
                   │    │            │   │       └ <TupleCompatibleCommand create-group>
                   │    │            │   └ <function Context.forward at 0x7f21c852e670>
                   │    │            └ <click.core.Context object at 0x7f21c8814e80>
                   │    └ <class 'dbt_meshify.change.ChangeSet'>
                   └ typing.List
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 804, in forward
    return __self.invoke(__cmd, *args, **kwargs)
                                 │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
                                 └ ()
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
                       └ ()
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/cli.py", line 123, in wrapper_decorator
    return func(*args, **kwargs)
           │     │       └ {'select': ('+cart_detail',), 'owner_name': 'David RH', 'name': 'shopping', 'exclude': (), 'group_yml_path': None, 'owner_ema...
           │     └ ()
           └ <function create_group at 0x7f21c45065e0>
> File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/main.py", line 565, in create_group
    changes: ChangeSet = grouper.add_group(
                         │       └ <function ResourceGrouper.add_group at 0x7f21c4563550>
                         └ <dbt_meshify.utilities.grouper.ResourceGrouper object at 0x7f21c15d8220>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/utilities/grouper.py", line 140, in add_group
    group, resources = self._generate_resource_group(
                       │    └ <function ResourceGrouper._generate_resource_group at 0x7f21c4563430>
                       └ <dbt_meshify.utilities.grouper.ResourceGrouper object at 0x7f21c15d8220>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/utilities/grouper.py", line 87, in _generate_resource_group
    nodes = self.project.select_resources(
            │    │       └ <function DbtProject.select_resources at 0x7f21c455e8b0>
            │    └ <dbt_meshify.dbt_projects.DbtProject object at 0x7f21c15ae190>
            └ <dbt_meshify.utilities.grouper.ResourceGrouper object at 0x7f21c15d8220>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/dbt_projects.py", line 330, in select_resources
    results = self.dbt.ls(self.path, args, output_key=output_key)
              │    │   │  │    │     │                └ 'unique_id'
              │    │   │  │    │     └ ['--select', ('+cart_detail',)]
              │    │   │  │    └ PosixPath('/home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo')
              │    │   │  └ <dbt_meshify.dbt_projects.DbtProject object at 0x7f21c15ae190>
              │    │   └ <function Dbt.ls at 0x7f21c454ca60>
              │    └ <dbt_meshify.dbt.Dbt object at 0x7f21c4513250>
              └ <dbt_meshify.dbt_projects.DbtProject object at 0x7f21c15ae190>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/dbt.py", line 57, in ls
    return self.invoke(directory, args)
           │    │      │          └ ['ls', '--select', ('+cart_detail',), '--output', 'json', '--output-keys', 'unique_id']
           │    │      └ PosixPath('/home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo')
           │    └ <function Dbt.invoke at 0x7f21c520daf0>
           └ <dbt_meshify.dbt.Dbt object at 0x7f21c4513250>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt_meshify/dbt.py", line 33, in invoke
    raise result.exception
          │      └ TypeError("descriptor 'split' for 'str' objects doesn't apply to a 'tuple' object")
          └ dbtRunnerResult(success=False, exception=TypeError("descriptor 'split' for 'str' objects doesn't apply to a 'tuple' object"),...
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt/cli/main.py", line 88, in invoke
    result, success = cli.invoke(dbt_ctx)
                      │   │      └ <click.core.Context object at 0x7f21c15d8430>
                      │   └ <function MultiCommand.invoke at 0x7f21c8534d30>
                      └ <Group cli>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1686, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
              │   │            │         │            └ <click.core.Context object at 0x7f21c15d8430>
              │   │            │         └ ['--output', 'json', '--output-keys', 'unique_id']
              │   │            └ 'ls'
              │   └ <function BaseCommand.make_context at 0x7f21c852eaf0>
              └ <Command list>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 943, in make_context
    self.parse_args(ctx, args)
    │    │          │    └ ['--output', 'json', '--output-keys', 'unique_id']
    │    │          └ <click.core.Context object at 0x7f21c15d8490>
    │    └ <function Command.parse_args at 0x7f21c8534790>
    └ <Command list>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/core.py", line 1405, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
          │                   │      │               └ ['--output', 'json', '--output-keys', 'unique_id']
          │                   │      └ <function OptionParser.parse_args at 0x7f21c8517d30>
          │                   └ <click.parser.OptionParser object at 0x7f21c15d8d00>
          └ ['--output', 'json', '--output-keys', 'unique_id']
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/parser.py", line 337, in parse_args
    self._process_args_for_options(state)
    │    │                         └ <click.parser.ParsingState object at 0x7f21c15d8c70>
    │    └ <function OptionParser._process_args_for_options at 0x7f21c8517e50>
    └ <click.parser.OptionParser object at 0x7f21c15d8d00>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/parser.py", line 364, in _process_args_for_options
    self._process_opts(arg, state)
    │    │             │    └ <click.parser.ParsingState object at 0x7f21c15d8c70>
    │    │             └ '--select'
    │    └ <function OptionParser._process_opts at 0x7f21c851f0d0>
    └ <click.parser.OptionParser object at 0x7f21c15d8d00>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/parser.py", line 514, in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
    │    │               │              │               └ <click.parser.ParsingState object at 0x7f21c15d8c70>
    │    │               │              └ None
    │    │               └ '--select'
    │    └ <function OptionParser._match_long_opt at 0x7f21c8517ee0>
    └ <click.parser.OptionParser object at 0x7f21c15d8d00>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/click/parser.py", line 419, in _match_long_opt
    option.process(value, state)
    │      │       │      └ <click.parser.ParsingState object at 0x7f21c15d8c70>
    │      │       └ ('+cart_detail',)
    │      └ <function MultiOption.add_to_parser.<locals>.parser_process at 0x7f21c45f7700>
    └ <click.parser.Option object at 0x7f21c15f1190>
  File "/home/david/Documents/demo-dbt-meshify/venv/lib/python3.9/site-packages/dbt/cli/options.py", line 38, in parser_process
    value_list = str.split(value, " ")
                           └ ('+cart_detail',)

TypeError: descriptor 'split' for 'str' objects doesn't apply to a 'tuple' object
14:31:20 | ERROR | Error creating group: shopping
```

### System information
**Which database are you using dbt with?**
- [ ] DuckDb
- [ ] Postgres 16

**The output of `dbt debug`:**
```
14:36:11  Running with dbt=1.6.6
14:36:11  dbt version: 1.6.6
14:36:11  python version: 3.9.5
14:36:11  python path: /home/david/Documents/demo-dbt-meshify/venv/bin/python3.9
14:36:11  os info: Linux-5.4.0-163-generic-x86_64-with-glibc2.31
14:36:12  Using profiles dir at /home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo
14:36:12  Using profiles.yml file at /home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo/profiles.yml
14:36:12  Using dbt_project.yml file at /home/david/Documents/demo-dbt-meshify/DuckDB-DBT-Example/demo/dbt_project.yml
14:36:12  adapter type: duckdb
14:36:12  adapter version: 1.6.1
14:36:12  Configuration:
14:36:12    profiles.yml file [OK found and valid]
14:36:12    dbt_project.yml file [OK found and valid]
14:36:12  Required dependencies:
14:36:12   - git [OK found]

14:36:12  Connection:
14:36:12    database: local_duckdb_project_db
14:36:12    schema: duckdb_demo
14:36:12    path: ../local_duckdb_project_db.duckdb
14:36:12    config_options: None
14:36:12    extensions: None
14:36:12    settings: None
14:36:12    external_root: .
14:36:12    use_credential_provider: None
14:36:12    attach: None
14:36:12    filesystems: None
14:36:12    remote: None
14:36:12    plugins: None
14:36:12    disable_transactions: False
14:36:12  Registered adapter: duckdb=1.6.1
14:36:12    Connection test: [OK connection ok]

14:36:12  All checks passed!
```

```
15:48:35  Running with dbt=1.6.6
15:48:35  dbt version: 1.6.6
15:48:35  python version: 3.9.5
15:48:35  python path: /home/david/Documents/meshify_test/venv/bin/python3.9
15:48:35  os info: Linux-5.4.0-163-generic-x86_64-with-glibc2.31
15:48:35  Using profiles dir at /home/david/Documents/meshify_test/DuckDB-DBT-Example/demo
15:48:35  Using profiles.yml file at /home/david/Documents/meshify_test/DuckDB-DBT-Example/demo/profiles.yml
15:48:35  Using dbt_project.yml file at /home/david/Documents/meshify_test/DuckDB-DBT-Example/demo/dbt_project.yml
15:48:35  adapter type: postgres
15:48:35  adapter version: 1.6.6
15:48:35  Configuration:
15:48:35    profiles.yml file [OK found and valid]
15:48:35    dbt_project.yml file [OK found and valid]
15:48:35  Required dependencies:
15:48:35   - git [OK found]

15:48:35  Connection:
15:48:35    host: localhost
15:48:35    port: 5432
15:48:35    user: dbt_user
15:48:35    database: dbt_demo
15:48:35    schema: dbt_schema
15:48:35    connect_timeout: 10
15:48:35    role: None
15:48:35    search_path: None
15:48:35    keepalives_idle: 0
15:48:35    sslmode: None
15:48:35    sslcert: None
15:48:35    sslkey: None
15:48:35    sslrootcert: None
15:48:35    application_name: dbt
15:48:35    retries: 1
15:48:35  Registered adapter: postgres=1.6.6
15:48:35    Connection test: [OK connection ok]

15:48:35  All checks passed!
```

**The output of `dbt --version`:**
```
Core:
  - installed: 1.6.6
  - latest:    1.6.6 - Up to date!

Plugins:
  - duckdb: 1.6.1 - Up to date!
```

### Additional context
I've tried this on a few variations of my project

### Are you interested in contributing the fix?
I'm happy to run things after making any changes suggested.

**Comment by d-roman-halliday** [comment]
I attempted repeating the same process in a different environment with the same outcome.

```
16:34:23  Running with dbt=1.6.6
16:34:23  dbt version: 1.6.6
16:34:23  python version: 3.11.2
16:34:23  python path: /Users/davidroman-halliday/eclipse-Meshify/meshify-demo/venv/bin/python3.11
16:34:23  os info: macOS-13.6-arm64-arm-64bit
16:34:23  Using profiles dir at /Users/davidroman-halliday/eclipse-Meshify/meshify-demo
16:34:23  Using profiles.yml file at /Users/davidroman-halliday/eclipse-Meshify/meshify-demo/profiles.yml
16:34:23  Using dbt_project.yml file at /Users/davidroman-halliday/eclipse-Meshify/meshify-demo/dbt_project.yml
16:34:23  adapter type: duckdb
16:34:23  adapter version: 1.6.1
16:34:23  Configuration:
16:34:23    profiles.yml file [OK found and valid]
16:34:23    dbt_project.yml file [OK found and valid]
16:34:23  Required dependencies:
16:34:23   - git [OK found]

16:34:23  Connection:
16:34:23    database: local_duckdb_project_db
16:34:23    schema: duckdb_demo
16:34:23    path: ../local_duckdb_project_db.duckdb
16:34:23    config_options: None
16:34:23    extensions: None
16:34:23    settings: None
16:34:23    external_root: .
16:34:23    use_credential_provider: None
16:34:23    attach: None
16:34:23    filesystems: None
16:34:23    remote: None
16:34:23    plugins: None
16:34:23    disable_transactions: False
16:34:23  Registered adapter: duckdb=1.6.1
16:34:23    Connection test: [OK connection ok]

16:34:23  All checks passed!
```

**Comment by nicholasyager** [comment]
Thanks for submitting this issue, @d-roman-halliday! I believe this is caused by a change in how 1.6.x parses selectors. @dave-connors-3 has a PR up that should resolve this issue (#185).
